model:
  arch: minigpt4
  model_type: pretrain_vicuna0
  max_txt_len: 160
  end_sym: "###"
  low_resource: True
  prompt_template: "###Human: {} ###Assistant: "
  llama_model: "/path/to/vicuna-7b"  # TODO: set path to Vicuna/LLaMA model
  ckpt: "/path/to/minigpt4_checkpoint.pth"  # TODO: set path to MiniGPT-4 checkpoint

datasets:
  cc_sbu_align:
    vis_processor:
      train:
        name: "blip2_image_eval"
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"

evaluation_datasets:
  iconvqa:
    eval_file_path: "/path/to/iconvqa/choose_text_val.json"  # TODO: set path to annotation file
    img_path: "/path/to/iconvqa/iconvqa_images"  # TODO: set path to images folder
    max_new_tokens: 20
    batch_size: 1

run:
  task: image_text_pretrain
  name: minigpt4_iconvqa_eval
  save_path: "/path/to/save/folder"
